# zset -g @tmux_power_theme 'redwine'
# run-shell ~/.tmux-power/tmux-power.tmux


set -g status-style bg=#0d0d0d,fg=#8b0000
set -g status-left "#[fg=#0d0d0d,bg=#8b0000,bold]  berhan@#h #[fg=#8b0000,bg=#1a1a1a] #S "
set -g status-right "#[fg=#8b0000,bg=#1a1a1a] %T #[fg=#0d0d0d,bg=#8b0000,bold] %F "
set -g window-status-format "#[fg=#555555,bg=#0d0d0d] #I:#W "
set -g window-status-current-format "#[fg=#8b0000,bg=#1a1a1a,bold] #I:#W "
set -g status-left-length 50
set -g status-right-length 50
